appointment/urls.py
from .views import AppointmentView
from django.urls import path, include
app_name = 'appointments'
urlpatterns = [
   path('', AppointmentView.as_view(), name='make_appointment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('pages/', include('django.contrib.flatpages.urls')),
   path('news/', include('simpleapp.urls')),
   path('', include('protect.urls')),
   path('sign/', include('sign.urls')),
   path('accounts/', include('allauth.urls')),
   path('appointments/', include(('appointment.urls', 'appointments'), namespace='appointments')),
]

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me

urlpatterns = [
    path('login/',LoginView.as_view(template_name = 'sign/login.html'),name='login'),
    path('logout/',LogoutView.as_view(template_name = 'sign/logout.html'),name='logout'),
    path('signup/',BaseRegisterView.as_view(template_name = 'sign/signup.html'),name='signup'),
    path('upgrade/', upgrade_me, name='upgrade')
]

simpleapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.urls import reverse
from django.core.cache import cache

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def update_rating(self):
        posts_rating = self.posts.aggregate(pr=Coalesce(Sum('rating'), 0))['pr']
        comments_rating = self.user.comments.aggregate(cr=Coalesce(Sum('rating'), 0))['cr']
        posts_comments_rating = self.posts.aggregate(pcr=Coalesce(Sum('comment__rating'), 0))['pcr']

        self.rating = posts_rating * 3 + comments_rating + posts_comments_rating
        self.save()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    subscribers = models.ManyToManyField(User, related_name='subscribed_categories', blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):

    news = 'NE'
    article = 'AR'

    POST_TYPES = [
        (news, 'Новости'),
        (article, 'Статья')
    ]
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='posts')
    post_type = models.CharField(max_length=2, choices=POST_TYPES, default=news)
    post_time = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=255)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.text) > 124:
            return self.text[0:124] + '...'
        else:
            return self.text 

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.title.title()}:{self.preview()}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'news-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.category.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    comment_time = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

templates/appointment_created.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ appointment.client_name }} Спасибо за запись!</h2>
    <p> Вы записаны на {{ appointment.date|date:"d-M-Y" }} по вопросу: {{ appointment.message|truncatechars:50 }} </p>
</body>
</html>

templates/default.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Новостной портал</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Simple SignUp/SignIn app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>News Portal</h1>
                <p class="lead">Сайт разрабатывается</p>
                <p>Версия 1</p>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Новостной портал</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">Simple SignUp/SignIn app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>News Portal</h1>
                <p class="lead">Сайт разрабатывается</p>
                <p>Версия 1</p>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/make_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Make an appointment</title>
</head>
<body>
    <h1>Make an appointment</h1>
    <form action="{% url 'appointments:make_appointment' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="client_name">Your name</label>
        <input type="text" name="client_name"><br>
        <label for="message">Short description of your issue</label>
        <input type="text" name="message"><br>
        <label for="date">Choose time</label>
        <input type="date" name="date">.<br>
        <input type="submit">
    </form>
</body>
</html>

templates/post_create.html
{% extends 'default.html' %}

{% block content %}
<h1>Новость</h1>
<button style="margin-top: 10px"> <a href="/news/"> К новостям</a> </button>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/post_detail.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load censor_filters %}
<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <h1>Новость</h1>
{% if post %}
    <table>
        <tr>
            <td><u>Заголовок</u></td>
            <td><u>Содержание</u></td>
            <td><u>Дата публикации</u></td>
        </tr>
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.text|censor }}</td>
            <td>{{ post.post_time|date:'d M Y' }}</td>
            {% endif %}
        </tr>
    </table>
<button style="margin-top: 10px"> <a href="/news/"> Страница с новостями</a> </button>
{% endblock content%}
</body>

templates/post_edit.html
{% extends default.html' %}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_list.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load censor_filters %}
{% load custom_tags %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <div style="margin: 20px;"> <!-- Обернул все содержимое в блок с отступами -->
        <h1>Все новости</h1>
        {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
        <form action="" method="get" style="margin-bottom: 20px;"> <!-- Отступ между формой и таблицей -->
            {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
            {{ filterset.form.as_p }}
            {# Добавим кнопку отправки данных формы #}
            <input type="submit" value="Найти" />
        </form>
        <button style="margin-top: 10px"> <a href="/news/categorys/"> Список категорий</a> </button>
        <button style="margin-top: 10px"> <a href="/news/create/"> Сделать пост</a> </button>
        <table width="100%" border="1" cellspacing="0" cellpadding="10">
            <thead>
                <tr>
                    <th width="20%">Категория</th>
                    <th width="20%">Заголовок</th>
                    <th width="20%">Дата публикации</th>
                    <th width="20%">Содержание</th>
                    <th width="20%">Тип публикации</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                <tr>
                    <td>
                        {% for category in post.category.all %}
                            {{ category.name }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ post.title }}</td>
                    <td>{{ post.post_time }}</td>
                    <td>{{ post.text|truncatechars:21|censor }}</td>
                    <td>{{ post.get_post_type_display }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        {# Пагинация #}
        {% if page_obj.has_previous %}
            <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
        {% endif %}

        {% if page_obj.has_next %}
            <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
        {% endif %}
    </div>
{% endblock content %}
</body>

templates/search.html
{% extends 'default.html'%}
{% load custom_filters %}
{% load censor_filters %}
{% load custom_tags %}

<head>
    <meta charset="UTF-8">
    <title>News</title>
</head>
<body>
{% block content %}
    <h1>Все новости</h1>
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
    <table>
        <tr>
            <td><u>Заголовок</u></td>
            <td><u>Дата публикации</u></td>
            <td><u>Содержание</u></td>
        </tr>
        {% for post in posts %}
        <tr>
            <td>{{ post.title }}</td>
            <td>{{ post.post_time }}</td>
            <td>{{ post.text|truncatechars:21|censor }}</td>
        </tr>
        {% endfor %}
    </table>
{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
{% endif %}

{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
{% endif %}

{% endblock content%}
</body>